config/routes.rb
require "router_constraints"

Store::Application.routes.draw do
  use_doorkeeper
  api_actions = [:index, :create, :update, :show]

  devise_for :super_admin_user,
    path: "super_admin",
    controllers: {
      sessions: "super_admin/sessions"
    }

  devise_for :admin_users,
    path: "admin",
    path_names: {
      sign_up: false
    },
    controllers: {
      registrations: "admin/devise/registrations",
      sessions: "admin/devise/sessions"
    }

  devise_for :people,
    controllers: {
      registrations: "store/devise/registrations",
      sessions: "store/devise/sessions"
    }

  devise_scope :admin_user do
    get "subscription" => "admin/devise/registrations#new", as: :subscription
  end

  resource :subscription_wizard, only: [:show, :update], controller: "subscription_wizard"

  namespace :consultor do
    resources :home, only: [:index]

    root :to => 'home#index'
  end

  namespace :super_admin, path: "super_admin" do
    resource :dashboard, controller: 'dashboard', only: [:show]
    resources :stores, only: [:index]
    resources :themes, controller: 'themes'

    root :to => 'dashboard#show'
  end

  namespace :pos do
    namespace :api do
      scope "/v1" do
        resource  :status,            only: :show, controller: "status"
        resources :inventory_items,   only: [:index]
        resources :orders,            only: api_actions
        resources :carts,             only: api_actions
        resources :cart_items,        only: api_actions.push(:destroy)
        resources :customers,         only: api_actions
        resource  :store_reports,     only: [:show]
        resources :cash_entries,      only: api_actions

        if Rails.env.development? || Rails.env.test?
          resource :resources, only: [:show]
        end
      end
    end
  end

  namespace :admin do
    namespace :api do
      scope "/v1" do
        resources :manufacturers,     only: [:index]
        resources :taxonomies,        only: [:index]
        resource  :status,            only: :show, controller: "status"
        resources :mustache_commands, only: [:index]
        resources :theme_files,       only: [:index, :update]
      end
    end
  end

  namespace :admin do
    resource :dashboard, controller: "dashboard" do
      get 'index' => 'dashboard#index'
    end

    resources :theme_editor, only: [:show], controller: "theme_editor"
    resources :theme_preview, only: [:show], controller: "theme_preview" do
      collection do
        delete :destroy
      end
    end

    resources :orders, only: [:index, :show, :update, :create]

    resource :settings, only: [:show, :update] do
      resource :payment_methods,
        controller: 'payment_methods', only: :show, module: 'settings' do

        resource :pagseguro_wizard,
          only: [:show, :update],
          controller: 'payment_methods/pagseguro_wizard'
      end

    end
    resources :taxonomies, only: [:index, :create, :update, :destroy]
    resources :reports, only: :index do
      collection do
        get :inventory
        get :sales
      end
    end
    resources :store_themes, only: [:index, :update, :create]
    resources :pages, except: [:show]
    resource  :company_contact, only: [:edit, :update]
    resources :banners

    resources :marketing, only: [:index]

    resource :inventory do
      resources :custom_fields, controller: 'inventory/custom_fields'

      resources :items, controller: 'inventory/items' do
        collection do
          resource :search, controller: 'inventory/items/search', only: [] do
            post "index"
            post "for_adding_entry"
          end
        end

        resources :entries, controller: 'inventory/entries',
          only: [:index, :new, :create, :edit, :update, :destroy]

        resources :images, controller: 'inventory/items/images',
          only: [:index, :destroy, :create, :update]
      end
    end

    namespace :store do
      get 'dashboard' => 'dashboard#index'
    end

    resources :people
    resources :users # admin_users

    namespace :offline, module: "offline" do
      resources :sales, only: :new
      root :to => 'sales#new'
    end

    root :to => 'dashboard#index'
  end

  namespace :mobile_admin, module: "mobile_admin" do
    resource :inventory do
      resources :items, controller: 'inventory/items' do
        resources :images, controller: 'inventory/items/images',
          only: [:index, :destroy, :create, :update]
      end
    end

    root to: 'inventory/items#index'
  end

  #
  # MAIN STORE PAGE
  #
  constraints RouterConstraints::Store.new do
    resource :cart, only: [:show, :update], controller: "store/cart" do
      resource :shipping_cost, only: [:create], controller: "store/cart/shipping_cost"
    end

    resources :categories, only: [:show], controller: "store/categories"
    resources :products, only: [:index, :show], controller: "store/products"
    resources :pages,    only: [:show], controller: "store/pages"
    resource  :contact,  only: [:new, :create], controller: "store/contact" do
      get :success
    end

    resource :cart_items, only: [:create, :destroy], controller: "store/cart_items"

    namespace :checkout, module: 'store/checkout' do
      resource :shipping, only: [:show, :update], controller: "shipping"
      resource :payment,  only: [:show], controller: "payment"
      resource :success,  only: [:show], controller: "success"
    end

    namespace :gateway_notifications, module: 'store/gateway_notifications' do
      resource :pagseguro, only: :create, controller: "pagseguro"
    end

    root :to => 'store/home#index', as: "root"
  end

  #
  # MARKETING PAGE
  #
  constraints RouterConstraints::Marketing.new do
    get 'consultores' => 'marketing/consultores#show'
    get 'precos'      => 'marketing/pricing#show'
    get 'api'         => 'marketing/api#show'
    namespace :marketing do
      resources :home, only: [:index]
    end
    root :to => 'marketing/home#index', as: :marketing_root
  end
end

app/models/taxonomy.rb
class Taxonomy < ActiveRecord::Base
  extend Models::Extensions::FullTextSearch

  acts_as_tree order: "name"

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :store, foreign_key: 'store_id', class_name: "Company"
  has_and_belongs_to_many :custom_fields

  attr_accessible :name, :parent, :parent_id, :store_id

  validates :name, presence: true

  def self.hash_tree_for_homepage(depth = 2)
    self.hash_tree(limit_depth: depth)
  end

  # .flat_hash_tree
  #
  # converts this:
  #
  #   anakin: { vader: {},
  #             luke:  {} },
  #   ben:    {}
  #
  # in:
  #
  #   [ anakin, vader, luke, ben ]
  #
  # returns all nodes in a flat array
  def self.flat_hash_tree(tree = self.hash_tree, result = [])
    tree.each do |node, children|
      result << node
      if children.present?
        self.flat_hash_tree(children, result)
      end
    end
    result
  end

  def self.search_for(query)
    search do
      fields :name
      keywords query
    end
  end
end

app/controllers/admin/api/taxonomies_controller.rb
# encoding: utf-8
class Admin::Api::TaxonomiesController < Admin::Api::ApplicationController
  skip_before_filter :authenticate_api_token

  def index
    taxonomies = current_company.taxonomies
    taxonomies = search(taxonomies)
    taxonomies = limit(taxonomies)

    render json: taxonomies
  end
end

app/controllers/admin/taxonomies_controller.rb
class Admin::TaxonomiesController < Admin::ApplicationController
  def index
    @taxonomies = current_company.taxonomies.hash_tree
    @taxonomy = Taxonomy.new
  end

  def create
    @taxonomy = current_company.taxonomies.new(params[:taxonomy])
    flash = if @taxonomy.save
              { notice: I18n.t("admin.default_messages.create.success") }
            else
              { alert: I18n.t("admin.default_messages.create.failure") }
            end
    redirect_to admin_taxonomies_path, flash
  end

  def update
    @taxonomy = current_company.taxonomies.friendly.find(params[:id])
    flash = if @taxonomy.update_attributes(params[:taxonomy])
              { notice: I18n.t("admin.default_messages.update.success") }
            else
              { alert: I18n.t("admin.default_messages.update.failure") }
            end
    redirect_to admin_taxonomies_path, flash
  end

  def destroy
    current_company.taxonomies.friendly.find(params[:id]).destroy
    redirect_to admin_taxonomies_path, notice: I18n.t("admin.default_messages.delete.success")
  end
end

app/helpers/admin/taxonomies_helper.rb
module Admin::TaxonomiesHelper
  def html_select_collection(taxonomy)
    taxonomy.map do |e|
      nesting = ""
      e.depth.times { nesting << "&nbsp;&nbsp;&nbsp;" }
      option_name = "#{nesting} #{e.name}"
      [ raw(option_name), e.id ]
    end
  end

  def render_taxonomies(nodes)
    result = ""
    has_children = ""
    node_html = ""

    nodes.each do |node, children|
      has_children = children.present? ? 'has_children' : ''
      node_html += render("admin/taxonomies/node", node: node)

      if children.present?
        node_html+= raw render_taxonomies(children)
      end

    end
    result+= content_tag :div, class: "child #{has_children}" do
      raw node_html
    end

    raw result
  end
end

app/views/admin/taxonomies/_new_node_form.html.erb
<div class="node_form js_new_node_form">
  <%= simple_form_for [:admin, taxonomy] do |f| %>
    <% if node.present? %>
      <%= f.input :parent_id, as: :hidden, input_html: { value: node.id } %>
    <% end %>

    <% label = node.present? ? "#{t(".new_subcategory_label")} #{node.name}" : t(".new_category_label") %>
    <%= f.input :name,
      as: :string,
      label: label,
      required: false,
      hint: false %>
    <%= f.submit %>
  <% end %>
</div>

app/views/admin/taxonomies/_node.html.erb
<div class="node js_node" data-node-id="<%= node.id %>">

  <% # the node itself %>
  <div class="box name">
    <%= node.name %>
  </div>

  <% # the options when you hover a node %>
  <div class="node_options">
    <div class="button js_show_edit_node_form">
      <%= link_to image_tag("admin/icons/edit_16.png"), "", id: "show_edit_node_form" %>
    </div>
    <div class="button js_show_new_node_form">
      <%= link_to image_tag("admin/icons/plus_16.png"), "", id: "show_new_node_form" %>
    </div>
    <div class="button delete_category">
      <%= link_to image_tag("admin/icons/trash.png"),
        admin_taxonomy_path(node),
        data: {confirm: t("admin.generic.confirm")},
        method: :delete %>
    </div>
  </div>

  <% # form for new node %>
  <%= render "new_node_form", taxonomy: @taxonomy, node: node %>

  <% # form for updating the node %>
  <div class="node_form js_edit_node_form">
    <%= simple_form_for [:admin, node] do |f| %>
      <%= f.input :name,
        as: :string,
        required: false,
        hint: false %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/taxonomies/_tree_content_template.html.erb
<div class="child has_children">
  <div class="node js_node" data-node-id="3">
    <div class="box">Masculino</div>
  </div>

  <div class="child has_children">
    <div class="node js_node" data-node-id="4">
      <div class="box">Fardamentos</div>
    </div>

    <div class="child has_children">
      <div class="node js_node" data-node-id="20">
        <div class="box">Futebol</div>
      </div>

      <div class="child">
        <div class="node js_node" data-node-id="22">
          <div class="box">Grêmio</div>
        </div>
        <div class="node js_node" data-node-id="23">
          <div class="box">Flamengo</div>
        </div>
        <div class="node js_node" data-node-id="24">
          <div class="box">Fluminense</div>
        </div>
      </div>

      <div class="node js_node" data-node-id="21">
        <div class="box">Vôlei</div>
      </div>
    </div>

    <div class="node js_node" data-node-id="4">
      <div class="box">Meias</div>
    </div>

    <div class="child">
      <div class="node js_node" data-node-id="25">
        <div class="box">Esporte</div>
      </div>
      <div class="node js_node" data-node-id="26">
        <div class="box">Social</div>
      </div>

      <div class="child">
        <div class="node js_node" data-node-id="26">
          <div class="box">Social</div>
        </div>
      </div>
    </div>

    <div class="node js_node" data-node-id="5">
      <div class="box">Calças</div>
    </div>

    <div class="node js_node" data-node-id="50">
      <div class="box">Saias</div>
    </div>
  </div>
</div>

<div class="child has_children">
  <div class="node js_node" data-node-id="8">
    <div class="box">Whatever</div>
  </div>

  <div class="child has_children">
    <div class="node js_node" data-node-id="9">
      <div class="box">Camisa</div>
    </div>

    <div class="child has_children">
      <div class="node js_node" data-node-id="9">
        <div class="box">Camisa</div>
      </div>

      <div class="child">
        <div class="node js_node" data-node-id="9">
          <div class="box">Camisa</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="child has_children">
  <div class="node js_node" data-node-id="8">
    <div class="box">Femininas</div>
  </div>

  <div class="child">
    <div class="node js_node" data-node-id="9">
      <div class="box">Camisa</div>
    </div>
    <div class="node js_node" data-node-id="10">
      <div class="box">Camisetas</div>
    </div>
  </div>
</div>

<div class="child">
  <div class="node js_node" data-node-id="80">
    <div class="box">Canoagem</div>
  </div>
</div>

app/views/admin/taxonomies/index.html.erb
<%= view_header %>

<header>
  <h1><%= t('.title') %></h1>
</header>

<div class="main_container">
  <p>
    <%= t('.intro') %>
  </p>

  <% if @taxonomies.empty? %>
    <p>
      <%= t('.first_instructions') %>
    </p>
  <% end %>

  <div class="js_tree_diagrams tree_diagrams">
    <div class="js_tree_body" data-create-url="<%= admin_taxonomies_url %>">

      <div class="greatfather has_children">
        <div class="node js_node greatfather_node">
          <div class="box"><%= t('.greatfather_node') %></div>
        </div>

        <%= render_taxonomies(@taxonomies) %>


        <div class="node js_node" data-node-id="">
          <% # the node itself %>
          <div class="box name">
            <%= link_to image_tag("admin/icons/plus_16.png"), "", id: "show_new_node_form" %>
          </div>

          <% # form for new node %>
          <%= render "new_node_form", taxonomy: @taxonomy, node: nil %>
        </div>
      </div>
    </div>
  </div>

  <% unless @taxonomies.empty? %>
    <br />
    <br />
    <strong>Dica:</strong> <%= simple_format t('.normal_instructions') %>
  <% end %>
</div>