config/routes.rb
require "router_constraints"

Store::Application.routes.draw do
  use_doorkeeper
  api_actions = [:index, :create, :update, :show]

  devise_for :super_admin_user,
    path: "super_admin",
    controllers: {
      sessions: "super_admin/sessions"
    }

  devise_for :admin_users,
    path: "admin",
    path_names: {
      sign_up: false
    },
    controllers: {
      registrations: "admin/devise/registrations",
      sessions: "admin/devise/sessions"
    }

  devise_for :people,
    controllers: {
      registrations: "store/devise/registrations",
      sessions: "store/devise/sessions"
    }

  devise_scope :admin_user do
    get "subscription" => "admin/devise/registrations#new", as: :subscription
  end

  resource :subscription_wizard, only: [:show, :update], controller: "subscription_wizard"

  namespace :consultor do
    resources :home, only: [:index]

    root :to => 'home#index'
  end

  namespace :super_admin, path: "super_admin" do
    resource :dashboard, controller: 'dashboard', only: [:show]
    resources :stores, only: [:index]
    resources :themes, controller: 'themes'

    root :to => 'dashboard#show'
  end

  namespace :pos do
    namespace :api do
      scope "/v1" do
        resource  :status,            only: :show, controller: "status"
        resources :inventory_items,   only: [:index]
        resources :orders,            only: api_actions
        resources :carts,             only: api_actions
        resources :cart_items,        only: api_actions.push(:destroy)
        resources :customers,         only: api_actions
        resource  :store_reports,     only: [:show]
        resources :cash_entries,      only: api_actions

        if Rails.env.development? || Rails.env.test?
          resource :resources, only: [:show]
        end
      end
    end
  end

  namespace :admin do
    namespace :api do
      scope "/v1" do
        resources :manufacturers,     only: [:index]
        resources :taxonomies,        only: [:index]
        resource  :status,            only: :show, controller: "status"
        resources :mustache_commands, only: [:index]
        resources :theme_files,       only: [:index, :update]
      end
    end
  end

  namespace :admin do
    resource :dashboard, controller: "dashboard" do
      get 'index' => 'dashboard#index'
    end

    resources :theme_editor, only: [:show], controller: "theme_editor"
    resources :theme_preview, only: [:show], controller: "theme_preview" do
      collection do
        delete :destroy
      end
    end

    resources :orders, only: [:index, :show, :update, :create]

    resource :settings, only: [:show, :update] do
      resource :payment_methods,
        controller: 'payment_methods', only: :show, module: 'settings' do

        resource :pagseguro_wizard,
          only: [:show, :update],
          controller: 'payment_methods/pagseguro_wizard'
      end

    end
    resources :taxonomies, only: [:index, :create, :update, :destroy]
    resources :reports, only: :index do
      collection do
        get :inventory
        get :sales
      end
    end
    resources :store_themes, only: [:index, :update, :create]
    resources :pages, except: [:show]
    resource  :company_contact, only: [:edit, :update]
    resources :banners

    resources :marketing, only: [:index]

    resource :inventory do
      resources :custom_fields, controller: 'inventory/custom_fields'

      resources :items, controller: 'inventory/items' do
        collection do
          resource :search, controller: 'inventory/items/search', only: [] do
            post "index"
            post "for_adding_entry"
          end
        end

        resources :entries, controller: 'inventory/entries',
          only: [:index, :new, :create, :edit, :update, :destroy]

        resources :images, controller: 'inventory/items/images',
          only: [:index, :destroy, :create, :update]
      end
    end

    namespace :store do
      get 'dashboard' => 'dashboard#index'
    end

    resources :people
    resources :users # admin_users

    namespace :offline, module: "offline" do
      resources :sales, only: :new
      root :to => 'sales#new'
    end

    root :to => 'dashboard#index'
  end

  namespace :mobile_admin, module: "mobile_admin" do
    resource :inventory do
      resources :items, controller: 'inventory/items' do
        resources :images, controller: 'inventory/items/images',
          only: [:index, :destroy, :create, :update]
      end
    end

    root to: 'inventory/items#index'
  end

  #
  # MAIN STORE PAGE
  #
  constraints RouterConstraints::Store.new do
    resource :cart, only: [:show, :update], controller: "store/cart" do
      resource :shipping_cost, only: [:create], controller: "store/cart/shipping_cost"
    end

    resources :categories, only: [:show], controller: "store/categories"
    resources :products, only: [:index, :show], controller: "store/products"
    resources :pages,    only: [:show], controller: "store/pages"
    resource  :contact,  only: [:new, :create], controller: "store/contact" do
      get :success
    end

    resource :cart_items, only: [:create, :destroy], controller: "store/cart_items"

    namespace :checkout, module: 'store/checkout' do
      resource :shipping, only: [:show, :update], controller: "shipping"
      resource :payment,  only: [:show], controller: "payment"
      resource :success,  only: [:show], controller: "success"
    end

    namespace :gateway_notifications, module: 'store/gateway_notifications' do
      resource :pagseguro, only: :create, controller: "pagseguro"
    end

    root :to => 'store/home#index', as: "root"
  end

  #
  # MARKETING PAGE
  #
  constraints RouterConstraints::Marketing.new do
    get 'consultores' => 'marketing/consultores#show'
    get 'precos'      => 'marketing/pricing#show'
    get 'api'         => 'marketing/api#show'
    namespace :marketing do
      resources :home, only: [:index]
    end
    root :to => 'marketing/home#index', as: :marketing_root
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include Models::Extensions::UUID

  uuid field: "uuid"

  # TODO - remove this crap
  attr_accessible :cart_id, :store_id, :customer_id, :items_attributes, :items,
                  :environment, :uuid, :payment_type, :admin_user_id,
                  :customer, :store, :shipping_address, :shipping_details, :total

  belongs_to :customer, class_name: "Person"
  belongs_to :admin_user
  belongs_to :cart
  belongs_to :store, class_name: "Company"
  has_many :items, class_name: "OrderItem"
  has_many :payment_statuses, ->{ order("id asc") }
  has_one :shipping_details, class_name: "OrderShipping"
  has_one :shipping_address, as: :addressable, class_name: "Address"

  VALID_ENVIRONMENTS = [:website, :offline]
  VALID_PAYMENT_TYPES = [:cash, :debit, :credit_card, :installments]

  validates :environment,
    inclusion: { in: VALID_ENVIRONMENTS + VALID_ENVIRONMENTS.map(&:to_s) },
    allow_blank: true

  validates :payment_type,
    inclusion: { in: VALID_PAYMENT_TYPES + VALID_PAYMENT_TYPES.map(&:to_s) },
    allow_blank: true

  accepts_nested_attributes_for :items

  scope :created_on_the_website, ->{ where(environment: "website") }
  scope :created_offline, ->{ where(environment: "offline") }

  def self.create_offline(params)
    create(params.merge(environment: :offline))
  end

  def current_payment_status
    payment_statuses.current_status
  end

  def items_quantity
    items.parent_items.map(&:quantity).reduce(:+)
  end

  def summary
    if paid?
      if    items.some_shipped_some_pending? then :paid_some_shipped_some_pending
      elsif items.all_pending_shipment?      then :paid_pending_all_shipments
      elsif items.all_shipped?               then :paid_and_shipped
      elsif items.all_cancelled?             then :paid_but_shipment_cancelled
      end
    elsif payment_statuses.cancelled?
      :cancelled
    else
      :pending_payment
    end
  end

  def paid?
    @paid = payment_statuses.paid?
  end

  def number
    self.id
  end
end

app/controllers/admin/api/orders_controller.rb
# encoding: utf-8
class Admin::Api::OrdersController < Admin::Api::ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @resources = current_company.orders.includes(:payment_statuses).order('id desc')
    @resources = @resources.created_offline

    @resources = @resources.where(payment_type: params[:payment_type]) if params[:payment_type]

    only_current_user_resources
    search_by_date
    paginate_resource
    render json: @resources, meta: meta
  end

  def create
    cart = current_company.carts.find_by_uuid(order_params[:cart_id])

    sale = Store::Sale.new(cart,
                           uuid: order_id,
                           admin_user_id: current_user.id,
                           payment_type: payment_type)
    sale.close

    render json: sale.order, include_items: true
  end

  private

  def order_id
    order_params[:id]
  end

  def payment_type
    order_params[:payment_type]
  end

  def order_params
    params
      .require(:order)
      .permit(:id, :cart_id, :payment_type, :created_at)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def index
    environment = params[:environment] || "website"
    orders = current_company
      .orders
      .includes(:payment_statuses)
      .where(environment: environment)
      .order('id desc')
      .last(50)

    @orders = Admin::OrderDecorator.decorate_collection(orders)
  end

  def show
    order = current_company.orders.find(params[:id])
    @order = Admin::OrderDecorator.decorate(order)
  end

  def edit
  end

  def update
    @order = current_company.orders.find(params[:id])

    if @order.update_attributes(params[:order])
      redirect_to admin_order_url(@order)
    else
      @order = Admin::OrderDecorator.decorate(@order)
      render "show"
    end
  end
end

app/controllers/pos/api/orders_controller.rb
# encoding: utf-8
class Pos::Api::OrdersController < Pos::Api::ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @resources = current_company.orders.includes(:payment_statuses).order('id desc')
    @resources = @resources.created_offline

    @resources = @resources.where(payment_type: params[:payment_type]) if params[:payment_type]

    only_current_user_resources
    search_by_date
    paginate_resource
    render json: @resources, meta: meta, root: "orders", include: 'customer,cart'
  end

  def create
    cart = current_company.carts.find_by_uuid(order_params[:cart_id])

    sale = Store::Sale.new(cart,
                           uuid: order_uuid,
                           admin_user_id: current_user.id,
                           payment_type: payment_type)
    sale.close

    render json: sale.order, include_items: true
  end

  private

  def order_uuid
    order_params[:uuid]
  end

  def payment_type
    order_params[:payment_type]
  end

  def order_params
    deserializer = ActiveModel::Deserializer.new(params)
    resource_params = deserializer
      .require(:orders)
      .permit(:id, :payment_type, :created_at)
      .associations(:cart, :order_items)

    resource_params = replace_id_with_uuid(resource_params)
  end
end

app/views/admin/orders/_order_card.html.erb
<div class="order_card <%= order.summary %>" id="order_card_<%= order.id%>">
  <div class="card_containner">
    <div class="order_id">
      <div class="label">Número do pedido</div>
      <div class="value">
        <%= order.id %>
      </div>
    </div>

    <div class="payment_status <%= :paid if order.paid? %>">
      <%= t(".payment_statuses.#{order.current_payment_status}") %>
    </div>

    <div class="shipping_status <%= order.summary %>">
      <%= raw t(".shipping_summary.#{order.summary}") %>
    </div>

    <div class="details">
      <div class="total">
        <%= order.total %>
      </div>
      <div class="purchase_date">
        <%= order.purchase_date %>
      </div>
      <div class="items_quantity">
        <%= order.items_quantity == 1 ? "1 item" : "#{order.items_quantity} itens" %>
      </div>

      <div class="details_button">
        <%= small_button "Ver detalhes", admin_order_path(order) %>
      </div>
    </div>

  </div>
</div>

app/views/admin/orders/edit.html.erb
<h1>Admin::Orders#edit</h1>
<p>Find me in app/views/admin/orders/edit.html.erb</p>

app/views/admin/orders/index.html.erb
<%= view_header %>

<header>
  <h1><%= t('.title') %></h1>
</header>

<div class="main_container">
  <p>
    <span class="color_legend processing"> </span>
    Não requerem atenção neste momento

    <span class="color_legend requires_attention"> </span>
    Requerem atenção

    <span class="color_legend approved"> </span>
    Pedidos concluídos com sucesso
  </p>

  <% if params[:environment] != "website" %>
    <a href="?environment=website">Pedidos no site</a>
  <% else %>
    Pedidos no site
  <% end %>
  <br />
  <% if params[:environment] != "offline" %>
    <a href="?environment=offline">Pedidos offline</a>
  <% else %>
    Pedidos offline
  <% end %>
  <br />
  <br />

  <div class="order_cards">
    <% @orders.each_slice(5) do |orders_line| %>
      <div class="orders_line">
      <% orders_line.each do |order| %>
        <%= render "order_card", order: order %>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<%= view_header back_to: admin_orders_path %>

<header>
  <h1><%= t('.title') %><%= @order.number %></h1>
  <p>
    Pedido através
    <% if @order.environment == "website" %>
      da <strong>loja virtual</strong>
    <% elsif @order.environment == "offline" %>
      do <strong>ponto de venda</strong>
    <% end %>
  </p>
</header>

<div class="main_container">

  <%= simple_form_for @order, url: admin_order_path, method: :put do |f| %>

    <table class="properties">
      <tbody>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= t(".summary") %>:<br /></td>
          <td class="summary <%= @order.model.summary %>">
            <%= @order.summary_long_text %>
          </td>
        </tr>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= t(".created_at") %>:<br /></td>
          <td>
            <%= @order.created_at %>
          </td>
        </tr>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= t(".payment_status") %>:<br /></td>
          <td class="payment_status <%= @order.current_payment_status %>">
            <%= @order.payment_status_with_datetime %>
          </td>
        </tr>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= t(".shipping_details") %>:<br /></td>
          <td>
            <% if @order.shipping_details.present? %>
              <%= @order.shipping_details.complete_details %>
            <% else %>
              Não há informações de frete.
            <% end %>
          </td>
        </tr>

        <% if @order.shipping_details.present? %>
          <tr class="<%= cycle('even', 'odd') %>">
            <td></td>
            <td>
              <%= t('.package') %>:
              <%= @order.shipping_details.package_width %>cm,
              <%= @order.shipping_details.package_length %>cm,
              <%= @order.shipping_details.package_height %>cm,
              <%= @order.shipping_details.package_weight %>kg
              <%= t('.package_legend') %>
            </td>
          </tr>
          <tr class="<%= cycle('even', 'odd') %>">
            <td><%= t(".shipping_address") %>:<br /></td>
            <td>
              <%= @order.shipping_address.complete_address %>
            </td>
          </tr>
        <% end %>

        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= t(".total_amount") %>:<br /></td>
          <td> <%= @order.total %> (<%= t(".excluding_shipping") %>) </td>
        </tr>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= t(".client") %>:</td>
          <td>
            <% if @order.customer.present? %>
              <%= @order.customer.full_name %>,
              <%= @order.customer.email %>
            <% else %>
              Comprador não especificado.
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

    <br />
    <h2>Items no pedido</h2>
    <table class="listing">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Preço unitário</th>
          <% if @order.environment == "website" %>
            <th>Opções</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :items do |item_form| %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td> <%= item_form.object.id %> </td>
          <td> <%= item_form.object.name %> </td>
          <td> <%= item_form.object.price %> </td>

          <% if @order.environment == "website" %>
            <td class="options">

              <%= item_form.input :status,
                collection: statuses_collection,
                selected: item_form.object.model.status,
                include_blank: false %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>

    </table>

    <p>
      <%= f.submit id: "submit" %>
    </p>
  <% end %>
</div>