config/routes.rb
require "router_constraints"

Store::Application.routes.draw do
  use_doorkeeper
  api_actions = [:index, :create, :update, :show]

  devise_for :super_admin_user,
    path: "super_admin",
    controllers: {
      sessions: "super_admin/sessions"
    }

  devise_for :admin_users,
    path: "admin",
    path_names: {
      sign_up: false
    },
    controllers: {
      registrations: "admin/devise/registrations",
      sessions: "admin/devise/sessions"
    }

  devise_for :people,
    controllers: {
      registrations: "store/devise/registrations",
      sessions: "store/devise/sessions"
    }

  devise_scope :admin_user do
    get "subscription" => "admin/devise/registrations#new", as: :subscription
  end

  resource :subscription_wizard, only: [:show, :update], controller: "subscription_wizard"

  namespace :consultor do
    resources :home, only: [:index]

    root :to => 'home#index'
  end

  namespace :super_admin, path: "super_admin" do
    resource :dashboard, controller: 'dashboard', only: [:show]
    resources :stores, only: [:index]
    resources :themes, controller: 'themes'

    root :to => 'dashboard#show'
  end

  namespace :pos do
    namespace :api do
      scope "/v1" do
        resource  :status,            only: :show, controller: "status"
        resources :inventory_items,   only: [:index]
        resources :orders,            only: api_actions
        resources :carts,             only: api_actions
        resources :cart_items,        only: api_actions.push(:destroy)
        resources :customers,         only: api_actions
        resource  :store_reports,     only: [:show]
        resources :cash_entries,      only: api_actions

        if Rails.env.development? || Rails.env.test?
          resource :resources, only: [:show]
        end
      end
    end
  end

  namespace :admin do
    namespace :api do
      scope "/v1" do
        resources :manufacturers,     only: [:index]
        resources :taxonomies,        only: [:index]
        resource  :status,            only: :show, controller: "status"
        resources :mustache_commands, only: [:index]
        resources :theme_files,       only: [:index, :update]
      end
    end
  end

  namespace :admin do
    resource :dashboard, controller: "dashboard" do
      get 'index' => 'dashboard#index'
    end

    resources :theme_editor, only: [:show], controller: "theme_editor"
    resources :theme_preview, only: [:show], controller: "theme_preview" do
      collection do
        delete :destroy
      end
    end

    resources :orders, only: [:index, :show, :update, :create]

    resource :settings, only: [:show, :update] do
      resource :payment_methods,
        controller: 'payment_methods', only: :show, module: 'settings' do

        resource :pagseguro_wizard,
          only: [:show, :update],
          controller: 'payment_methods/pagseguro_wizard'
      end

    end
    resources :taxonomies, only: [:index, :create, :update, :destroy]
    resources :reports, only: :index do
      collection do
        get :inventory
        get :sales
      end
    end
    resources :store_themes, only: [:index, :update, :create]
    resources :pages, except: [:show]
    resource  :company_contact, only: [:edit, :update]
    resources :banners

    resources :marketing, only: [:index]

    resource :inventory do
      resources :custom_fields, controller: 'inventory/custom_fields'

      resources :items, controller: 'inventory/items' do
        collection do
          resource :search, controller: 'inventory/items/search', only: [] do
            post "index"
            post "for_adding_entry"
          end
        end

        resources :entries, controller: 'inventory/entries',
          only: [:index, :new, :create, :edit, :update, :destroy]

        resources :images, controller: 'inventory/items/images',
          only: [:index, :destroy, :create, :update]
      end
    end

    namespace :store do
      get 'dashboard' => 'dashboard#index'
    end

    resources :people
    resources :users # admin_users

    namespace :offline, module: "offline" do
      resources :sales, only: :new
      root :to => 'sales#new'
    end

    root :to => 'dashboard#index'
  end

  namespace :mobile_admin, module: "mobile_admin" do
    resource :inventory do
      resources :items, controller: 'inventory/items' do
        resources :images, controller: 'inventory/items/images',
          only: [:index, :destroy, :create, :update]
      end
    end

    root to: 'inventory/items#index'
  end

  #
  # MAIN STORE PAGE
  #
  constraints RouterConstraints::Store.new do
    resource :cart, only: [:show, :update], controller: "store/cart" do
      resource :shipping_cost, only: [:create], controller: "store/cart/shipping_cost"
    end

    resources :categories, only: [:show], controller: "store/categories"
    resources :products, only: [:index, :show], controller: "store/products"
    resources :pages,    only: [:show], controller: "store/pages"
    resource  :contact,  only: [:new, :create], controller: "store/contact" do
      get :success
    end

    resource :cart_items, only: [:create, :destroy], controller: "store/cart_items"

    namespace :checkout, module: 'store/checkout' do
      resource :shipping, only: [:show, :update], controller: "shipping"
      resource :payment,  only: [:show], controller: "payment"
      resource :success,  only: [:show], controller: "success"
    end

    namespace :gateway_notifications, module: 'store/gateway_notifications' do
      resource :pagseguro, only: :create, controller: "pagseguro"
    end

    root :to => 'store/home#index', as: "root"
  end

  #
  # MARKETING PAGE
  #
  constraints RouterConstraints::Marketing.new do
    get 'consultores' => 'marketing/consultores#show'
    get 'precos'      => 'marketing/pricing#show'
    get 'api'         => 'marketing/api#show'
    namespace :marketing do
      resources :home, only: [:index]
    end
    root :to => 'marketing/home#index', as: :marketing_root
  end
end

app/controllers/admin/store/application_controller.rb
class Admin::Store::ApplicationController < Admin::ApplicationController
end

app/controllers/admin/store/dashboard_controller.rb
class Admin::Store::DashboardController < Admin::ApplicationController
  def index
    
  end
end

app/controllers/store/application_controller.rb
class Store::ApplicationController < ApplicationController
  layout "store"

  include ControllersExtensions::CartInstantiation
  include ControllersExtensions::Store::ViewObjects

  # e. g loads taxonomies, cart item quantities
  include ControllersExtensions::Resources

  def render(*args)
    # TODO - cache mustache layouts somehow. Average view load time in
    # development is around 45ms.
    super
  end
end

app/controllers/store/cart/shipping_cost_controller.rb
class Store::Cart::ShippingCostController < Store::ApplicationController
  skip_before_filter :load_taxonomies

  def create
    result = ::Store::CartShippingCalculation.create(self, shipping_options)
    if result.success?
      render json: {
        zipcode: {
          zipcode: params[:zipcode],
          cost:    Money.new(result.total).humanize,
          days:    result.days.to_s
        }
      }
    else
      render status: 422, json: { errors: [result.error_message] }
    end
  end

  private

  def shipping_options
    { destination_zipcode: params[:zipcode],
      type:                params[:type] }
  end
end

app/controllers/store/cart_controller.rb
class Store::CartController < Store::ApplicationController
  layout "store"

  before_filter :redirect_if_sales_disabled

  def show
    @checkout_enabled = Store::Policy::Checkout.new(self).enabled?
    @cart_items       = cart.current_items
    @cart             = DecorationBuilder.cart(cart.persistence)
    @shipping_calculation_enabled = current_store.has_zipcode?

    render "empty" and return if @cart_items.blank?
  end

  def update
    cart.update(params[:cart])
    ::Store::CartShippingCalculation.create(self, shipping_options)
    redirect_to cart_url
  end

  private

  def shipping_options
    { destination_zipcode: params[:zipcode],
      type:                params[:type] }
  end


  def redirect_if_sales_disabled
    redirect_to root_path unless current_store.sales_enabled?
  end
end

app/controllers/store/cart_items_controller.rb
class Store::CartItemsController < Store::ApplicationController
  skip_before_filter :load_taxonomies

  def create
    # FIXME an object that deals with controllers would better be named
    # differently, e.g Controllers::Store::CartItemsCreation
    inventory_item = current_store.items.friendly.find(params[:id])
    entry = Store::ItemsForWebsiteSale.new(self).item_for_cart(inventory_item)
    cart.add_item(entry)
    redirect_to cart_path
  end

  def destroy
    cart.remove_item(params[:id])
    redirect_to cart_path
  end
end

app/controllers/store/categories_controller.rb
class Store::CategoriesController < Store::ApplicationController
  def show
    @current_category = current_taxonomy
    @category = current_store.taxonomies.friendly.find(@current_category)

    items = Store::ItemsForWebsiteSale.new(self).items_for_category
    @items = Store::InventoryItemDecorator.decorate_collection(items)
  end

  def current_taxonomy
    params[:id]
  end
end

app/controllers/store/checkout/payment_controller.rb
module Store
  module Checkout
    class PaymentController < Store::CheckoutBaseController
      skip_before_filter :load_taxonomies

      def show
        if cart.persistence.zipcode_mismatch?
          ::Store::CartShippingCalculation.create(self, shipping_options)
        end

        sale = Store::Sale.new(cart.persistence)
        sale.close

        reset_cart
        session[:last_order_id] = sale.order.id
        pagseguro = Store::Payment::Pagseguro::Checkout.new(self, sale.order)
        pagseguro.create_transaction

        redirect_to pagseguro.payment_url
      rescue InventoryEntry::NegativeQuantity => e
        Store::Order::Items::OutOfStockAdjustment.new(cart.persistence).adjust
        redirect_to cart_path, alert: t("store.errors.checkout.entry_with_negative_quantity")
      end

      def after_payment_return_url(gateway)
        { pagseguro: checkout_success_url }[gateway]
      end

      private

      def shipping_options
        { destination_zipcode: cart.persistence.shipping.zipcode,
          type:                cart.persistence.shipping.service_type }
      end
    end
  end
end

app/controllers/store/checkout/shipping_controller.rb
module Store
  module Checkout
    class ShippingController < Store::CheckoutBaseController
      before_filter :define_cart_persistence

      def show
        @cart.set_customer(current_customer)
        @zipcode_mismatch = @cart.zipcode_mismatch?
        prepare_show_view
      end

      def update
        if use_custom_shipping_address?
          if @cart.update_attributes(params[:cart])
            redirect_to checkout_payment_url and return
          else
            prepare_show_view
            render :show
          end
        else
          Store::Cart::AddressDefinition.new(self, @cart).use_customers_default_address
          redirect_to checkout_payment_url and return
        end
      end

      private

      def prepare_show_view
        @cart.build_shipping_address
        @customer_address = @cart.customer.default_address
      end

      def use_custom_shipping_address?
        params[:place_order_with_custom_shipping_address] == "1"
      end

      def define_cart_persistence
        @cart = cart.persistence
      end
    end
  end
end

app/controllers/store/checkout/success_controller.rb
module Store
  module Checkout
    class SuccessController < Store::ApplicationController
      def show
        @order_id = session[:last_order_id]
      end
    end
  end
end

app/controllers/store/checkout_base_controller.rb
class Store::CheckoutBaseController < Store::ApplicationController
  before_filter :act_as_target_after_sign_up
  before_filter :authenticate_person!
  before_filter :redirect_on_empty_cart

  def act_as_target_after_sign_up
    session[:redirect_after_sign_in_or_up] = request.env["PATH_INFO"]
  end

  def redirect_on_empty_cart
    if cart.total_unique_items == 0
      redirect_to cart_url, alert: "Carrinho está vazio."
    end
  end
end

app/controllers/store/contact_controller.rb
class Store::ContactController < Store::ApplicationController
  def new
    @contact = ContactForm.new
  end

  def create
    @contact = ContactForm.new(params[:contact_form].merge({to: company_email}))

    if @contact.deliver
      redirect_to success_contact_url
    else
      render :new
    end
  end

  private

  def company_email
    current_store.contact_email
  end
end

app/controllers/store/gateway_notifications/pagseguro_controller.rb
module Store
  module GatewayNotifications
    class PagseguroController < ApplicationController
      def create
        email = current_store.payment_gateway.email
        token = current_store.payment_gateway.token
        notification_code = params[:notificationCode]

        pagseguro_response = PagSeguro::Notification.new(email, token, notification_code)
        notification = Store::GatewayNotifications::PagseguroWrapper.new(pagseguro_response)

        Store::Order::StatusChange.change(notification)

        render nothing: true
      end
    end
  end
end

app/controllers/store/home_controller.rb
class Store::HomeController < Store::ApplicationController
  layout "store"

  def index
    products
    @banners[:main_page_central_rotative] = current_store.banners.main_page_central_rotative
  end
end

app/controllers/store/pages_controller.rb
class Store::PagesController < Store::ApplicationController
  def show
    page = current_store.pages.find(params[:id])
    @page = DecorationBuilder.pages(page)
  end
end

app/controllers/store/products_controller.rb
class Store::ProductsController < Store::ApplicationController
  def show
    product
  end

  def product
    entry = Store::ItemsForWebsiteSale.new(self).detailed_item_for_show_page(params[:id])
    @product ||= DecorationBuilder.inventory_items(entry)
  end
end

app/controllers/super_admin/stores_controller.rb
class SuperAdmin::StoresController < SuperAdmin::ApplicationController
  def index
    @stores = Company.all
  end
end

app/helpers/store/customer_registration_helper.rb
module Store::CustomerRegistrationHelper
  def load_customer_email
    params[:email].present? ? { value: params[:email] } : {}
  end
end

app/helpers/store/mustache_themes_helper.rb
module Store::MustacheThemesHelper
  def render_theme_layout(action_view_context)
    layout = View::StoreTheme::Layout.new(@store_view, action_view_context)
    render layout.layout_to_be_rendered
  end
end

app/helpers/store/navigation_helper.rb
# encoding: utf-8
module Store::NavigationHelper
  def current_page_class(path_id)
    "current" if url_for == path_id || controller_name == path_id
  end

  def controller_name
    params[:controller]
  end
end

app/views/layouts/store/_google_analytics.html.erb
<% if @google_analytics.enabled? && AppConfig.google_analytics? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= @google_analytics.tracking_id %>', '<%= @google_analytics.domain %>');
    ga('send', 'pageview');
  </script>
<% end %>

app/views/layouts/store/_navigation.html.erb
<% # FIXME - is this still used? %>
<ul>
  <li><%= link_to "Principal", root_path, class: current_page_class(root_path) %></li>

  <% unless @theme.has_feature?(:vertical_taxonomy_menu) %>
    <%= render "store/theme_features/taxonomy_with_button_menu" %>
  <% end %>

  <% @pages.each do |page| %>
    <li><%= link_to page.title, page_path(page), class: current_page_class(page_path(page)) %></li>
  <% end %>

  <% if @company.contact_email.present? %>
    <li><%= link_to "Contato", new_contact_path, class: current_page_class("store/contact"), id: "contact_path" %></li>
  <% end %>
</ul>

app/views/layouts/store/_pingdom_rum.html.erb
<script>
  var _prum = [['id', '5359b80aabe53ddf60868808'],
    ['mark', 'firstbyte', (new Date()).getTime()]];
    (function() {
      var s = document.getElementsByTagName('script')[0]
        , p = document.createElement('script');
      p.async = 'async';
      p.src = '//rum-static.pingdom.net/prum.min.js';
      s.parentNode.insertBefore(p, s);
    })();
</script>

app/views/layouts/store/_theme_preview_warning.html.erb
<div class="theme_preview_warning body_offset">
</div>
<div class="theme_preview_warning">
  Você está visualizando outro tema que não o da sua loja.
  <%= link_to "Clique para voltar ao tema original",
    admin_theme_preview_index_path,
    method: :delete
  %>
</div>

<script type="text/javascript">
  /**
   * Hides the theme preview warning when inside an iFrame (like the editor)
   */
  if (window.self !== window.top) {
    $(".theme_preview_warning").hide();
  }
</script>

app/views/layouts/store/non_mustache_layout.html.erb
<div id="header">
  <%= link_to root_path do %>
    <div class="title">
      <h1><%= @company.name %></h1>
      <p>Caring about your workplace.</p>
    </div>
  <% end %>
  <%= render "shared/top_cart_summary" %>
</div>

<div id="global"
  class="<%= @theme.feature_as_class(:vertical_taxonomy_menu) if @layout_constraints.show_vertical_taxonomy_menu? %>">

  <div id="navigation">
    <%= render "layouts/store/navigation" %>
  </div>

  <div class="site_body">
    <% if @theme.has_feature?(:vertical_taxonomy_menu) %>
      <% if @layout_constraints.show_vertical_taxonomy_menu? %>
        <%= render "store/theme_features/taxonomy_as_vertical_menu" %>
      <% end %>
    <% end %>

    <div id="content">
      <% if banners?(:main_page_central_rotative) %>
        <div class="main_page_central_transitional_banners">
          <%= banners(:main_page_central_rotative) %>
        </div>
        <% if banners_amount(:main_page_central_rotative) > 1 %>
          <div class='main_page_central_transitional_banners_navigation'>
          </div>
        <% end %>
      <% end %>

      <div id="main">
        <div class="main_container">
          <%= render "store/shared/error_messages" %>
          <%= yield %>
        </div>
      </div>

      <div id="complementary_content">
        <div class="complementary_content_container">
          <div class="all_pages_right_ad_banners">
            <%= banners(:all_pages_right, width: 200) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="global">
  <%= render "store/shared/page_footer" %>
</footer>